### PR TITLE
Issues/rcin 3330 multiprocess access control

### PR DESCRIPTION
**Pull request by jsuksl**
- prevent multiple processes from accessing the same data in the queue simultaneously by using "for update"

### CODE REVIEW

**Comment by yomik** [comment]
http://www.postgresql.org/docs/9.1/static/explicit-locking.html

13.3.4. Advisory Locks

SELECT pg_advisory_lock(id) FROM foo WHERE id > 12345 LIMIT 100; -- danger!

このケースは合ってると思います

**Comment by yomik** [comment]
これも参照
http://stackoverflow.com/questions/20115907/postgres-pg-try-advisory-lock-blocks-all-records

Whereの中にpg_tryadvisory_lockを入れるのが良くない気がする

**Comment by smihica** [comment]
Hi! @jsuksl @yomik Thanks for your contribution.
When I run test on this branch
=============================================
$ python3 ./test.py postgresql://tes:tes@localhost
OK enqueue 1
...
OK enqueue2 2
Traceback (most recent call last):
  File "./test.py", line 456, in <module>
    main()
  File "./test.py", line 448, in main
    multiprocess_tasks()
  File "./test.py", line 408, in multiprocess_tasks
    qsize = queue.qsize()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/queues.py", line 117, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
===================================================
And python2.7 up the same error.
Is there any other requirements?

And I'm afraid that I'm not sure what the problem you are trying to fix...
Any "deadlock" or something occurred?

**Comment by jsuksl** [comment]
@smihica 

> And python2.7 up the same error.
the error fixed by 98b26cc6a25ff064f410ef31568d85f2d3cd36e7

please, try again.

**Comment by smihica** [comment]
>  task is executed twice by two worker processes

Oh mjd ?!?!?

I certainly checked it (transaction safety on multiple-processing) many times when the beginning of this project. And the concept is the MOST IMPORTANT concept of this project.
Oh no.. This project was a junk for a long time...

I checked the test and without your change, the test certainly failed.
 Thank you very much to fix the problem. @jsuksl and @yomik

**Comment by jsuksl** [comment]
@smihica 

would you release py-q4pg 0.1.3?

**Comment by smihica** [comment]
I released it. https://pypi.python.org/pypi/py-q4pg/0.2.0

**Comment by jsuksl** [comment]
> I released it. https://pypi.python.org/pypi/py-q4pg/0.2.0

thank you!

**Comment by jsuksl** [comment]
let me try another solution proposed by @kwatch
```
Makoto Kuwata·Mar-23 21:12
mqの件ですが、根本の原因は、commit()する*前に* advisory lockを解除しているのが原因ではないでしょうか。
q4pg.pyのコードを見ると、deque_item()の中で、以下のようなコードがありました。

                 cur.execute(self.ack_sql % (res[0],))
                 if conn: conn.commit()
ここで、self.ack_sql に delete 文と pg_advisory_unlock() が含まれています。
そのため、conn.commit() するまえに pg_advisory_unlock() が実行され、ロックが解除されます。
よって、pg_advisory_unlock() が実行されてから conn.commit() が実行されるまでの間に、他のプロセスが同じレコードを取得してしまう可能性があります。
修正方法は、commit() してから pg_advisory_unlock() を呼ぶことです。
```

**Comment by smihica** [comment]
Thanks very much @jsuksl and @kwatch !!
I'll fix it later

**Pull request merged**
